<!DOCTYPE html>
<html lang="en-US">
<!--********************************************-->
<!--*       Generated from PreTeXt source      *-->
<!--*                                          *-->
<!--*         https://pretextbook.org          *-->
<!--*                                          *-->
<!--********************************************-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="robots" content="noindex, nofollow">
</head>
<body class="ignore-math">
<article class="li"><h3 class="heading">
<span class="type">Item</span><span class="space"> </span><span class="codenumber">29</span><span class="period">.</span>
</h3>A variation on the try-catch statement will automatically close an open resource when an exception occurs, such as an open file. This is called try-with-resources.</article><span class="incontext"><a href="section-132.html#li-374" class="internal">in-context</a></span>
</body>
</html>
